### PR TITLE
WIP: Support for second viewport

### LINKED ISSUE #622: Multiple viewports
Is it possible to make a cropper with multiple viewports in one cropper, so the result are two ore more cropped images at once?

### PR DESCRIPTION
**Pull request by michael-letcher**
Requires proper config props set.

Replacing `view2`, `width2` and `height2`.

Fixes #622

### CODE REVIEW

**Comment by michael-letcher** [comment]
Will also need to export two images as requested in the ticket.

**Comment by Chapjus** [comment]
Is this functionality still in development or are there already some implementations?

**Comment by marcelx180** [comment]
I had the same problem, but I got a solution!

-> You have to change some files:

croppie.js:
`if (self.options.viewport.view2) {
            viewport2 = self.elements.viewport2 = document.createElement('div');
            addClass(viewport2, 'cr-viewport-2');

            css(viewport2, {
                // Remove 4px due to border
                width: (self.options.viewport.width2 - 4) + 'px',
                height: self.options.viewport.height2 + 'px'
            });
            viewport2.setAttribute('tabindex', 0);

            viewport.appendChild(viewport2);
        }`

croppie.css:
`.croppie-container .cr-viewport-2 {
    position: absolute;
    border: dashed #fff;
    border-width: 1px 0;
    margin: auto;
    top: 0;
    bottom: 0;
    right: 0;
    left: 0;
    z-index: 0;
}`

After that, you are ready to set the second viewport:

viewport: {
     width: 300,
     height: 200,
     view2: {
          width2: 300,
          height2: 150
     },
     width2: 300,
     height2: 150


}

Best regards :D

**Comment by michael-letcher** [comment]
@Chapjus I'm no longer working on this. What I added was enough to support what we needed.

It's up to the owner or others whom might want this feature to complete and get it merged.

**Comment by michael-letcher** [comment]
@thedustinsmith any chance we can get some feedback on this?

**Pull request closed without merging**
