### PR TITLE
Fix Issue 397

### PR DESCRIPTION
**Pull request by lumer82**

### CODE REVIEW

**Comment by lumer82** [comment]
Fixing #397

**Comment by thedustinsmith** [comment]
Thanks for the PR.  Sorry for the delay.  Would you mind throwing an empty `imgData` declaration in the block above?  Perhaps on line 974?  After the move, it isn't being declared.  After that this PR looks great.  Thanks.  For future reference.  There's no need to minify and update the version.  Since there's usually multiple PR's per release, this causes more conflicts than it helps.

**Comment by lumer82** [comment]
Ok, sorry for the changed version and min.js. I needed it for a local deploy.
I reverted these changes and added imgData = null to the declaration block.

**Comment by thedustinsmith** [comment]
Not your fault.  I put it in the README, but that was more for my own purposes.  I can see why that'd be confusing.

Thanks for the PR, I'd like to pull it down and check a few things, but I don't see any reason why this shouldn't be in the next version.

**Comment by lumer82** [comment]
Great, thank you.

It was helpful in the README, so we already could use a fixed version locally.

**Pull request merged**
