### PR TITLE
Swapped translate3d for translate so that clip-path can be used to ma…

### PR DESCRIPTION
**Pull request by atgillette**
…sk the croppie elements.

### CODE REVIEW

**Comment by thedustinsmith** [comment]
Could you give more explanation as to why you think it should use `translate` instead of `translate3d`?  

I can't remember exactly, but I think we chose to use `translate3d` for performance benefits.

**Comment by atgillette** [comment]
Sure,

I want to hide the part of the picture that is outside of the viewport, like in [http://codepen.io/chriscoyier/pen/b7e1305250912d645cb9ab8fabea0f1c](http://codepen.io/chriscoyier/pen/b7e1305250912d645cb9ab8fabea0f1c).  When I tried to do the same with your library, it didn't work.  I found out that translate3d was the cause of the problem.

**Comment by thedustinsmith** [comment]
Interesting ... would you mind throwing your croppie demo in a code pen?  I'd be interested in seeing it.

Regardless, I'm wondering if it would be better to allow this variable to set on a case-by-case basis.  Something like calling `Croppie.settings.translate = 'translate';` before you instantiate any croppie instances. Although, before settling on that, I'd like to look around at how other plugins are currently doing it.

The reason I say this is, personally, I'd rather use `translate3d`, but I can see the necessity to use `translate`.  Apparently this clip-path bug requires it, and also we might be able to improve IE support.

What are your thoughts on something like this?

**Comment by atgillette** [comment]
Here's a demo, http://codepen.io/atgillette/pen/mVgEKz.  You'll have to resize the width of the browser to line up the croppie with the svg clip-path to see the effect.  Sorry, can't spend more time on it to correct the positioning issue.

As for using a variable to set the string, I have no problem with that.

**Comment by thedustinsmith** [comment]
I know it doesn't mean much a year after this was submitted, but I've added `Croppie.globals.translate` setting to adjust what css property we use.

Thanks for the submission.

**Pull request closed without merging**
