### PR TITLE
Fix UMD, export the whole Croppie class

### LINKED ISSUE #470: Changes to the Croppie constructor using npm and Webpack
## Expected Behavior
In previous versions it was possible to create a new Croppie instance using:
```
import Croppie from 'croppie';
var croppie = new Croppie(ref, opts);
```

## Actual Behavior
Following the latest update this is no longer possible, you need to use the following syntax for it to work:
```
import Croppie from 'croppie';
var croppie = new Croppie.Croppie(ref, opts);
```

Is this an intended change in how the library is supposed to be used with npm, or is there something wrong? 

## Steps to Reproduce the Problem

  1. install the npm package
  1. import Croppie and try to create a new instance

## Specifications
  - Browser: The problem is not browser specific
  - Version: Croppie 2.6.1

### PR DESCRIPTION
**Pull request by sarunint**
This is my proposal to #470.

Using a template from https://github.com/umdjs/umd/blob/master/templates/commonjsStrict.js.

# Browser globals

```html
<script src="croppie.js"></script>
```
```javascript
var croppie = new Croppie(...);
```

# CommonJS

```javascript
const Croppie = require('croppie');
const croppie = new Croppie(...);
```

# ES Modules

```javascript
import Croppie from 'croppie'
const croppie = new Croppie(...);
```

CC: @thedustinsmith, @oystehei please take a look!

Closes #470

### CODE REVIEW

**Comment by nolimits4web** [comment]
I disagree with ESM export, it must be the `default` export, because this library exports single class and nothing more, and default export is what we expect from such kind if lib. Things like `import *` and `import { Croppie }` will just confuse more. 

> default imports will look at the key "default" of the exported object.

This is some misunderstanding, correct ESM module must have `export default ...` and no object, no keys, nothing. Things like `exports.default`, `exports._default` are used more like a hacks in/for bundlers and plugins. Just a separate correct ESM module file must be provided in addition with `export default Croppie` declaration

**Comment by sarunint** [comment]
Thanks @nolimits4web, I'll take a look at this tomorrow!

**Comment by sarunint** [comment]
@nolimits4web What do you think about `module` field for `package.json` which is used by [webpack](https://webpack.js.org/configuration/resolve/#resolve-mainfields) and [Rollup](https://github.com/rollup/rollup/wiki/pkg.module)? It would require build pipeline for this package (maybe, I'm not sure). But I think it really nice.

Sidenote, I'm a big fan of Angular, which extensively uses this `module` field in its packages.

**Comment by thedustinsmith** [comment]
@sarunint I like the idea of using rollup and the pkg.module.  It's probably time to catch this library up to JS standards, but I just don't have as much time as I once did.  

What do you think about getting rid of the module definition all together (in the source file).  Then when releases are made, we will use rollup to create a umd definition and a esm definition.  Does that sound like it would work?

**Comment by sarunint** [comment]
Hi @thedustinsmith, @nolimits4web 

After some experiments, it seems that tools like Webpack, Rollup, TypeScript are all able to pick up CommonJS default export correctly.

I think this PR is ready for merging!

**Comment by mkurcius** [comment]
Hi, any news on this? :)

**Comment by thedustinsmith** [comment]
I should have time to merge this one in this week.  @mkurcius Can you pull from @sarunint 's branch and confirm the export works in your scenario?  I'd like to have a couple eyes on this one before merging it in, since I failed to do so last time.

**Comment by mkurcius** [comment]
I am not sure how to test it properly.

In my scenerio I use TypeScript and this issue is referenced in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/21928

**Comment by sarunint** [comment]
@thedustinsmith, even without #529, I still can't get it work. May be my UMD fix is not working somehow.

**Pull request merged**
