### PR TITLE
Fix enforce boundary

### PR DESCRIPTION
**Pull request by jlane9**
We were attempting to use the enforceBoundary toggle (knowing full well it was still experimental), but kept running into the issue where if the image was scaled out it would cause the image to be cropped and positioned all haphazardly. We think we've figured out the issue  was due to minimum sizes were being set ex. `width = Math.min(width, self._originalImageWidth);` because the images themselves would not get any smaller only the position would change.

### CODE REVIEW

**Comment by thedustinsmith** [comment]
Awesome - thanks for the PR.  I don't have any time this week, but I'll look at this first thing on Monday.

**Comment by BVazquezAlvarez** [comment]
Excellent. It works on my test proyect. This PR will fix issue #258

**Comment by jlane9** [comment]
Thanks @BVazquezAlvarez for finding the related issues, @thedustinsmith have you had a chance to review the PR?

**Comment by ericpoulinnz** [comment]
Thanks @jlane9 ! This fixed the issues I was having with enforceBoundary.

**Comment by mrfazolka** [comment]
It solves the problem for me also! Great job!

**Comment by BVazquezAlvarez** [comment]
@thedustinsmith Please, review this if you have time enough. It's a very important fix for enforce boundary.

**Comment by thedustinsmith** [comment]
Haven't forgotten about this one.  I've got time blocked off tomorrow.

**Pull request merged**
