### PR TITLE
Wrap calculations for enforceBoundary: false in a conditional

### PR DESCRIPTION
**Pull request by patrickng**
This is a quick fix for #247 and #325. There was a comment implying the offsets and calculations were only for enforceBoundary: false option - which caused problems for the default option of enforceBoundary: true.

Hope this helps!

### CODE REVIEW

**Comment by thedustinsmith** [comment]
Ha!  Nice catch.  Thanks for helping out.

**Comment by raykudo** [comment]
#293 seems resolved too.

**Comment by stupotmcdoodlepip** [comment]
Perfect, thanks guys :)

**Comment by benj3** [comment]
Seems there is a problem still with enforceBoundary disabled on mobile where if you pinch to zoomout and rotate the image it just returns a blank white box.

**Pull request merged**
