### PR TITLE
cleaner fix for #552

### PR DESCRIPTION
**Pull request by nicod-pc**

### CODE REVIEW

**Comment by thedustinsmith** [comment]
Thanks!  I don't have an ETA on when we'll make a release for this, but it'll definitely be in the next one.

**Comment by immondu** [comment]
You have merged it 14 days ago. Do you know when it will be released?

**Comment by iwt-nduesing** [comment]
Hi @thedustinsmith is there a plan for when the next release is created?

**Comment by thedustinsmith** [comment]
Done - sorry it took so long.

**Pull request merged**
